export const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

export const JWT = {
  ACCESS_TOKEN_TTL: "1h",
  REFRESH_TOKEN_TTL: "30d",
} as const;

export const RATE_LIMIT = {
  AUTH_MAX: 10,
  AUTH_WINDOW_MS: 60_000,
  API_MAX: 100,
  API_WINDOW_MS: 60_000,
} as const;

export const ERROR_CODES = {
  ENROLLMENT_ALREADY_EXISTS: "ENROLLMENT_ALREADY_EXISTS",
  ENROLLMENT_NOT_FOUND: "ENROLLMENT_NOT_FOUND",
  ENROLLMENT_EXPIRED: "ENROLLMENT_EXPIRED",
  COURSE_NOT_PUBLISHED: "COURSE_NOT_PUBLISHED",
  QUIZ_MAX_ATTEMPTS_EXCEEDED: "QUIZ_MAX_ATTEMPTS_EXCEEDED",
  CERTIFICATE_ALREADY_ISSUED: "CERTIFICATE_ALREADY_ISSUED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
} as const;
